services:
  market-data-test:
    build:
      context: .
      args:
        GITHUB_ACTOR:
        GITHUB_TOKEN:
    container_name: gnomepy-testing
    environment:
      - LISTING_ID=5
      - DURATION=3
      - OUTPUT_DIR=/app/output
      - PROXY_PORT=8765
      - STAGE=prod
      - GNOME_REGISTRY_API_KEY=Smr7Jrmr8j93MMymhYdebaoRbV2T6TkX7phGPnrd
    volumes:
      - ./output:/app/output
