services:
  market-data-test:
    build:
      context: .
      args:
        GITHUB_ACTOR:
        GITHUB_TOKEN:
    container_name: gnomepy-testing
    environment:
      - LISTING_ID=8
      - DURATION=10
      - OUTPUT_DIR=/app/output
      - PROXY_PORT=8765
      - STAGE=dev
      - GNOME_REGISTRY_API_KEY=9WPV7CfeqXa578yVYlxdG3kCPFzACr7YaMU0UVma
    volumes:
      - ./output:/app/output
